import "@/app/globals.css";
import "@/app/assets/materialize.css";
import "@/app/assets/style.css";
import MainHeader from "@/components/main-header/main-header";

export const metadata = {
  title: "Good To Have",
  description: "Generated by create next app",
};

export default function FrontedLayout({ children }) {
  return (
    <html lang="zh-tw">
      <body>
        <MainHeader />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
