import "@/app/globals.css";
import "@/app/assets/materialize.css";
import "@/app/assets/style.css";
import MainHeader from "@/components/main-header/main-header";

export const metadata = {
  title: "GOOD TO HAVE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-tw">
      <body>{children}</body>
    </html>
  );
}
