import "@/app/globals.css";
import "@/app/asset/materialize.css";
import "@/app/asset/style.css";
import MainHeader from "@/components/main-header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-tw">
      <body>
        <MainHeader />
        {children}
      </body>
    </html>
  );
}
